### ISSUE TITLE
SnoopCompile 1.6.0 is broken

### ISSUE THREAD

**Issue by aminya** [timholy/SnoopCompile.jl#105]
We registered the inner packages, but we did not find time to check if the master will work when the inner packages are registered. We had [a hack script that solved this issue](https://github.com/timholy/SnoopCompile.jl/pull/98/commits/bb56316297de70d401e84433bf84064cd9cee9fe), but by removing it now we have a broken master that is tagged as 1.6. 

I think we should have registered the inner packages first, and then registered the top-level package separately.

Also, I am getting the error in #104, which we were not getting it before the split.

**Comment by KristofferC** [comment]
Definitely don't do something like https://github.com/timholy/SnoopCompile.jl/pull/98/commits/bb56316297de70d401e84433bf84064cd9cee9fe

**Comment by timholy** [comment]
Closed by #107

**Comment by aminya** [comment]
Now that 1.6.1 is registered, I still get errors when running the script online:
https://github.com/JuliaMusic/MusicXML.jl/runs/805777098

```
ERROR: LoadError: ArgumentError: Package SnoopCompileBot not found in current path:
- Run `import Pkg; Pkg.add("SnoopCompileBot")` to install the SnoopCompileBot package.
```

**Comment by KristofferC** [comment]
> Apparently, Pkg.add("SnoopCompile") does not add the subdirs. 

This doesn't make any sense. It adds the package `SnoopCompile`.

> This is a breaking change for the bot API if we have to wait for Pkg to fix this in some later Julia version.

Just to set expectations, there is nothing to fix in Pkg here. To try to explain this more, there is nothing more special about the relation SnoopCompile <-> SnoopCompileBot than it is to SnoopCompileBot <-> YAML. And just because you add SnoopCompileBot, it doesn't mean that YAML is somehow available to use. If you want to use YAML you add it, if you want to use SnoopCompileBot you add it.

Also, I want to reiterate that https://github.com/aminya/SnoopCompile.jl/blob/depsbuild/deps/build.jl is completely wrong. The build script runs in a separate temporary environment and will not have an effect on the current one. Calling `Pkg` functions in the build script is fundamentally not what you want to do.

**Comment by aminya** [comment]
Thanks for the answers. I want all the sub-packages to be available under the global environment. For backward compatibility, I need to add a script to add those sub-packages inside SnoopCompile.

I think something like this will solve the problem:
```julia
run(`julia -e 'using Pkg; Pkg.add("SnoopCompileCore"); Pkg.add("SnoopCompileAnalysis"); Pkg.add("SnoopCompileBot)'`)
```

**Comment by aminya** [comment]
> 
> Also, I want to reiterate that [aminya/SnoopCompile.jl:deps/build.jl@`depsbuild`](https://github.com/aminya/SnoopCompile.jl/blob/depsbuild/deps/build.jl?rgh-link-date=2020-06-25T07%3A40%3A30Z) is completely wrong. The build script runs in a separate temporary environment and will not have an effect on the current one. Calling `Pkg` functions in the build script is fundamentally not what you want to do.

I need the packages to be available in the global environment. My scripts run in an external process. Probably if I run `Pkg.activate()` before adding these, they will hopefully be available in the global environment.

**Comment by timholy** [comment]
@aminya, my point is that we called this release 1.6.0. The intent was that old scripts should continue to work. If they don't work, we have to do some compatibility work. It's not fair to ask everyone who has been using SnoopCompile to change their scripts for a 1.5->1.6 transition. It's quite important that we do this. Otherwise we really needed to call that release 2.0, but we didn't.

It's of course fine to also move towards a new way of doing things, but the whole meaning of backwards-compatible is that the old ways have to continue working without modification.

Can we get a fix out soon?

**Comment by aminya** [comment]
I don't know what to do at this point. I am literally [adding the package before using it](https://github.com/aminya/SnoopCompile.jl/blob/usingSnoopCompile/SnoopCompileBot/src/snoop_bot.jl#L113
), and it still errors
```
        using Pkg
        Pkg.add("SnoopCompileBot")
        
        using SnoopCompileBot
```
https://github.com/aminya/AcuteML.jl/runs/812754650?check_suite_focus=true#step:5:1

**Comment by timholy** [comment]
No, don't do that! I showed you how to set up your local machine in https://github.com/timholy/SnoopCompile.jl/issues/105#issuecomment-649345931, where:
- you're using `dev`ved versions of SnoopCompile and all its submodules, BUT
- your environment *only* knows about SnoopCompile itself

This is the key thing to replicate the environment that your "clients" will have, while also allowing you to try code locally that has not been registered. (Your clients will not have that problem because they will get the new code *after* it has been registered.) Do this, then **do not touch your environment anymore**.

Then, fix SnoopCompile so that the scripts work.

**Comment by aminya** [comment]
[This error](https://github.com/timholy/SnoopCompile.jl/issues/105#issuecomment-650423722) is happening online, and so their environment is clean! I am not using a `dev` version here. I am testing the end-result online. 

With [my final brute-force solution](https://github.com/timholy/SnoopCompile.jl/issues/105#issuecomment-650423722) failing, I have no clue what to do.

What does this mean? Does it mean that people cannot run `using SnoopCompileBot` in some environment? Is there a way to add a package to the global environment, and `using` it in an external process? These submodules might be different from normal packages, which makes all of these problems.

**Comment by timholy** [comment]
```julia
using SnoopCompile
@snoopi stuff
```
still works. So do that for now. Don't use the submodules directly until you can get it working with the meta-package.
