### ISSUE TITLE
Compile time data consistency

### ISSUE THREAD

**Issue by ehsantn** [timholy/SnoopCompile.jl#2]
I am trying to measure the compile times of different functions in our package (to be released soon). 

The total compile time is around 70s, but the sum of the first column of SnoopCompile's output is 4.3s. This is assuming that the output is in nanoseconds since uv_hrtime() is used underneath. Could you explain this? Does it take the number of times a function is compiled into account?

**Comment by timholy** [comment]
Great question, and I don't really know the answer because I didn't do that comparison myself (duh).

Are you on julia 0.3 or julia 0.4? (This is somewhat orthogonal with the "package precompilation" that's built into 0.4.) How are you measuring? I would expect the most relevant comparison would be summed-SnoopCompile-time vs. the difference between the first and second run of `@time include("runtests.jl")`. (The second run should have little/no compile time, so the difference is presumably the JITting time.)

**Comment by ehsantn** [comment]
I see! SnoopCompile doesn't measure type inference time. My problem is mostly in type inference. Do you know how I can measure type inference times?

I'm on bleeding edge master branch, BTW.

**Comment by timholy** [comment]
You can insert similar timing signals into `typeinf_uncached` I imagine.

**Comment by ehsantn** [comment]
Ok, thanks for the pointer.
