### ISSUE TITLE
latest version of `SnoopPrecompile` breaks `RecipesBase`

### ISSUE THREAD

**Issue by t-bltg** [timholy/SnoopCompile.jl#317]
@timholy, https://github.com/JuliaPlots/Plots.jl/issues/4597.

**Comment by timholy** [comment]
By way of explanation, see https://github.com/JuliaLang/julia/issues/47902

**Comment by t-bltg** [comment]
No harm done here, stuff like that happen ;)
I have a simplified reproducer, will open a PR in a moment.

**Comment by timholy** [comment]
Did you test whether putting it in the `@precompile_setup` block worsened your outcomes? I'm loathe to add restrictions but we could in SnoopPrecompile 2, if it improved outcomes elsewhere.

There's no immediate rush on this, and indeed I'm comfortable with waiting a bit. The bigger picture is that I'm currently tracking down cases in which the native-code caching doesn't give as much of a benefit as I think it should. SnoopPrecompile 1.0.2 was supposed to be part of the solution, but it's clearly not the whole solution. Since I have that locally and can use it in trying to figure out what the other causes are, it's fine if we wait a bit to see what additional clarity about root causes brings.

**Comment by t-bltg** [comment]
Let's continue the discussion in https://github.com/timholy/SnoopCompile.jl/pull/318#issue-1498437547.
