### ISSUE TITLE
Not Very useful on 0.5

### ISSUE THREAD

**Issue by Keno** [timholy/SnoopCompile.jl#7]
0.5 signatures contain a lot of calls with `#` in them, which SnoopCompile ignores.

**Comment by timholy** [comment]
Interesting. It's been a while, so I'm not fresh on this, but I assume the problem is
```jl
julia> str = "a#b = 5"
"a#b = 5"

julia> parse(str)
:a
```
and that perhaps a solution is
```jl
julia> str2 = "symbol(\"a#b\") = 5"
"symbol(\"a#b\") = 5"

julia> parse(str2)
:(symbol("a#b") = begin  # none, line 1:
            5
        end)
```
However, what's the likelihood that we could turn this into a useful precompile statement? I'm guessing that functions with `#` somewhere are generated, and is it possible that they get compiled by some top-level call that *is* covered? A test would be to snoop while issuing a precompile directive.

I haven't tried this on julia-0.5, so examples might be helpful.

**Comment by Keno** [comment]
See [here](https://gist.github.com/Keno/1638282811d55b1a7f838cff5dbd2d75) for a sample compile dump on 0.5. The issue is that the function's type has a `#` in the name, e.g. `Base.==(Base.#==, Array{Any, 1}, Array{Any, 1})`. In most cases the correct precompile statement is probably the one without that argument, or perhaps even `precompile(Base.==,Tuple{typeof(Base.==),Array{Any, 1}, Array{Any, 1})`. Also cc @JeffBezanson.
